version: '3.5'

services:
  api:
    container_name: retrogames
    build:
      context: ./
      target: development
    env_file:
      - .env
    volumes:
      - ./:/go/src/main
    ports:
      - 8080:8080
    depends_on:
      - database

  database:
    container_name: db
    image: postgres
    env_file:
      - .env
    ports:
      - 5432:5432

networks:
  default:
    driver: bridge
