version: '3.5'

services:
  api:
    container_name: retrogames
    build:
      context: ./
      target: development
    env_file:
      - .env
    volumes:
      - ./:/go/src/main
    ports:
      - 8080:8080
    depends_on:
      - database

  database:
    container_name: db
    image: postgres
    env_file:
      - .env
    ports:
      - 5432:5432

  pg_admin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret
    ports:
      - 15432:80
    depends_on:
      - database

networks:
  default:
    driver: bridge
