version: '3.5'

services:
  api:
    container_name: retrogames
    build:
      context: ./
      target: development
    env_file:
      - .env
    volumes:
      - ./:/go/src/main
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    container_name: database
    image: postgres:alpine3.20
    env_file:
      - .env
    ports:
      - 5432:5432  
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@local.com.br
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 8081:80
    depends_on:
      - db

networks:
  default:
    driver: bridge
